# Generated by Django 4.2.28 on 2026-03-04 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_delete_year_alter_class_options_alter_course_options_and_more'),
        ('accounts', '0006_studentprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ERP_MANAGER', 'ERP Manager'), ('DEAN', 'Dean'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], max_length=20),
        ),
        migrations.CreateModel(
            name='DeanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deans', to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dean_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='deanprofile',
            constraint=models.UniqueConstraint(fields=('department',), name='unique_dean_per_department'),
        ),
    ]
