# Generated by Django 4.2.28 on 2026-03-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_role_deanprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ERP_MANAGER', 'ERP Manager'), ('ADMISSION_TEAM', 'Admission Team'), ('DEAN', 'Dean'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], max_length=20),
        ),
    ]
