# Generated by Django 6.0.3 on 2026-03-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_subject_options_alter_subject_code_and_more'),
        ('accounts', '0009_alter_customuser_role_parentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='academics.department'),
        ),
    ]
