# Generated by Django 4.2.28 on 2026-03-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['name'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('course', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('program', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('department', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('class_obj', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('course', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('semester', 'name')},
        ),
    ]
