# Generated by Django 6.0.3 on 2026-03-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_delete_year_alter_class_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text="Unique subject code (e.g., 'CS301'). Globally unique across all courses.", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text="Full subject name (e.g., 'Data Structures')", max_length=100),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='academics_s_code_3689e5_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['semester', 'name'], name='academics_s_semeste_d577c1_idx'),
        ),
    ]
