# Generated by Django 6.0.3 on 2026-03-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='slot_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
