# Generated by Django 6.0.3 on 2026-03-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_qr_attendance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='attendance__marked__aa864c_idx',
            old_name='att_record_marked_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancesession',
            new_name='attendance__date_42b5b2_idx',
            old_name='att_session_date_idx',
        ),
    ]
