# Generated by Django 4.2.28 on 2026-03-04 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_delete_year_alter_class_options_alter_course_options_and_more'),
        ('accounts', '0007_alter_customuser_role_deanprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionIncharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_section_incharges', to=settings.AUTH_USER_MODEL)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_incharge_assignment', to='academics.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_incharge_sections', to='accounts.teacherprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sectionincharge',
            constraint=models.UniqueConstraint(fields=('section',), name='unique_incharge_per_section'),
        ),
    ]
